backend/store/Sale/urls.py
from django.urls import path
from .views import (add_to_productcart, change_productcart,
                    delete_productcart, get_productcart, cart_page, submit_order)


urlpatterns = [
    path('submit-cart/', submit_order, name='submit_order'),
    path('cart/', cart_page, name='cart_page'),
    path('get-cart/', get_productcart, name='get_productcart'),
    path('add-cart/', add_to_productcart, name='add_to_productcart'),
    path('update-cart/', change_productcart, name='change_productcart'),
    path('delete-cart/', delete_productcart, name='delete_productcart'),
]

backend/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('app_base.urls', 'app_base'), namespace='app-base')),
    path('', include(('account.urls', 'account'), namespace='account')),
    path('', include(('social.urls', 'social'), namespace='social')),
    path('', include(('Sale.urls', 'Sale'), namespace='Sale')),
    path('admin/', admin.site.urls),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/Sale/models.py
from django.db import models
from app_base.models import Product
from django.contrib.auth import get_user_model
User = get_user_model()


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    publish_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.phone


class ProductCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(null=True)

backend/store/Sale/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .models import Cart, ProductCart
from rest_framework import status
from .serializer import ProductCartserializer


def cart_page(request):
    return render(request, 'cart.html')


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def add_to_productcart(request):
    if request.user:
        productid = request.POST.get('id')
        quantity = request.POST.get('quantity')
        if productid and quantity:
            if ProductCart.objects.filter(user=request.user, product_id=productid):
                obj = ProductCart.objects.filter(user=request.user, product_id=productid)
                myobj = obj.first()
                myobj.quantity += 1
                myobj.save()
                return Response({
                    'status': True,
                    'detail':
                    'اضافه شد'
                })
            else:
                ProductCart.objects.create(user=request.user, quantity=quantity, product_id=productid)
                return Response({
                    'status': True,
                    'detail':
                    'به سبد خرید اضافه شد.'
                })
        else:
            return Response({
                'status': False,
                'detail':
                'ایتدا یک محصول را وارد کنید'
            })
    else:
        return Response({
            'status': False,
            'detail':
            'ابتدا در سایت ثبت نام کنید.'
        })


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def change_productcart(request):
    product_cart_id = request.POST.get('id')
    quantity = request.POST.get('quantity')
    if quantity == 'increase':
        obj = ProductCart.objects.filter(id=product_cart_id)
        myobj = obj.first()
        myobj.quantity += 1
        myobj.save()
        return Response({
            'status': True,
            'detail':
            'اضافه شد'
        })
    elif quantity == 'decrease':
        obj = ProductCart.objects.filter(id=product_cart_id)
        myobj = obj.first()
        myobj.quantity -= 1
        myobj.save()
        return Response({
            'status': True,
            'detail':
            'کم شد'
        })

    else:
        return Response({
            'status': False,
            'detail':
            'تعریف نشده.'
        })


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def delete_productcart(request):
    product_cart_id = request.POST.get('id')
    if product_cart_id:
        ProductCart.objects.filter(id=product_cart_id).delete()
        return Response({
            'status': True,
            'detail':
            'حذف شد'
        })
    else:
        return Response({
            'status': True,
            'detail':
            'ابتدا محصول را انتخاب کنید'
        })


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_productcart(request):
    if request.user:
        obj = ProductCart.objects.filter(user=request.user)
        serializer = ProductCartserializer(obj, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    else:
        return Response({
            'status': True,
            'detail':
            'ابتدا در سایت ثبت نام کنید.'
        })


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def submit_order(request):
    if request.user:
        if ProductCart.objects.filter(user=request.user):
            if Cart.objects.filter(user=request.user):
                cartobj = Cart.objects.filter(user=request.user)
                obj = ProductCart.objects.filter(user=request.user)
                for obj1 in obj:
                    obj1.cart = cartobj.first()
                    obj1.save()
                return Response({
                    'status': True,
                    'detail':
                    'سفارش ابدیت شد.'
                })
            else:
                cart_obj = Cart.objects.create(user=request.user)
                obj = ProductCart.objects.filter(user=request.user)
                for obj1 in obj:
                    obj1.cart = cart_obj
                    obj1.save()
                return Response({
                    'status': True,
                    'detail':
                    'سفارش درست شد.'
                })
        else:
            return Response({
                'status': False,
                'detail':
                'هیچ محصولی ثبت نشده است.'
            })

    else:
        return Response({
            'status': False,
            'detail':
            'ابتدا در سایت ثبت نام کنید.'
        })

backend/store/Sale/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container-fluid">
	<div class="p-2 m-2 text-dark border-bottom" style="font-size:14px;">سبد خرید</div>
	<div class="row">
		<div class="col-8">
			<div id="cart-page-product" class="border bg-white m-2 p-2">
				<div class="p-1 m-1 border-bottom" style="font-size:14px;">ارسال عادی (2)</div>

				

			</div>
		</div>
		<div class="col-4"> 
			<div class="border bg-white m-2 p-2">
				<div class="p-2 m-1 border-bottom">
					<span class="text-secondary" style="font-size:14px;">قیمت کالا ها (2):</span>
					<span class="text-secondary" style="float:left;font-size:14px;">250,000 تومان</span>
				</div>
				<div class="p-2 m-1 border-bottom">
					<span class="text-secondary" style="font-size:14px;">هزینه ارسال:</span>
					<span class="text-secondary" style="float:left;font-size:14px;">وابسته به شهر</span>
				</div>
				<div class="p-2 m-1">
					<span class="text-dark" style="font-size:14px;">هزینه کل</span>
					<span class="text-dark" style="float:left;font-size:14px;">300,000 تومان</span>
				</div>
				<div class="p-2 m-1">
					<span class="text-dark" style="font-size:14px;">مبلغ قابل پرداخت</span>
					<span class="text-dark" style="float:left;font-size:14px;">350,000 تومان</span>
				</div>
				<div class="border bg-danger text-center text-white p-2 m-1" style="border-radius:5px;cursor:pointer;">ثبت سفارش</div>
			</div>
		</div>
	</div>
</div>


{% endblock content %}
{% block js %}
{{ block.super }}

<script>
	$.ajax({
		url: "{% url 'Sale:get_productcart' %}",
		type: "GET",
		headers: {
			"Authorization": "Token"+" "+window.localStorage.getItem('token'),
		},
		success: function(data) {
			if (data) {                   
				$.each(data, function(){
					html=`
					<div class="row p-4 border-bottom m-1">
					<div class="col-3 ml-0 pl-0">
					<img class="p-1" src="${$(this)[0]['product_img']}" width="150" alt="">
					</div>
					<div class="col-9 mr-0 pr-0">
					<div class="p-1" style="font-size:14px;">${$(this)[0]['product_name']}
					</div>
					<div class="p-1 text-secondary" style="font-size:13px;">
					<i class="fa fa-circle-o m-1"></i> سفید
					</div>
					<div class="p-1 text-secondary" style="font-size:13px;">
					<i class="fas fa-shield-alt m-1"></i> گارانتی ۱۸ ماهه مدیاپردازش
					</div>
					<div class="p-1 text-secondary" style="font-size:13px;">
					<i class="fas fa-store-alt m-1"></i> فروشگاه
					</div>
					<div class="p-1 text-secondary" style="font-size:13px;">
					<i class="fa fa-truck m-1"></i> ارسال توسط فروشگاه
					</div>
					<div class="p-1 text-secondary">
					<div class="border p-2 mt-2" style="width:7rem;border-radius:7px;">
					<span class="plus" id="${$(this)[0]['id']}" style="cursor:pointer;"><i class='fas fa-plus text-primary p-1' style="float:right;"></i></span>
					<span id="counter text-center" class="pr-3 mr-1">${$(this)[0]['quantity']}</span>
					<span class="minus" id="${$(this)[0]['id']}" style="cursor:pointer;"><i class='fas fa-minus text-primary p-1' style="float:left;"></i></span>
					</div>
					</div>
					<div class="text-center border p-1 m-1 text-secondary delete" id="${$(this)[0]['id']}" style="font-size:13px;cursor:pointer;width:5rem;float:right;border-radius:5px;"><i class="fa fa-trash text-danger ml-2" aria-hidden="true"></i> حذف</div>

					<div class="p-1 text-secondary" style="font-size:14px;">
					<div class="text-left">250,000 تومان</div>
					</div>
					</div>
					</div>`
					$('#cart-page-product').append(html);
				});
				$('#counter').append(data.length);
			}
			$('.delete').on('click', function(event) {  
				event.preventDefault();
				$.post({
					url: "http://127.0.0.1:8000/delete-cart/",
					data: {
						'id':$(this).attr('id'),
					},
					headers: {
						"Authorization": "Token"+" "+window.localStorage.getItem('token'),
					},
					success: function(response) {
						location.reload();
					},
					error: function(jqXHR, textStatus, errorThrown) {
						console.log(textStatus, errorThrown, jqXHR);
					}
				});
			});
			$('.plus').on('click', function(event) {  
				event.preventDefault();
				$.post({
					url: "http://127.0.0.1:8000/update-cart/",
					data: {
						'id':$(this).attr('id'),
						'quantity':'increase'
					},
					headers: {
						"Authorization": "Token"+" "+window.localStorage.getItem('token'),
					},
					success: function(response) {
						location.reload();
					},
					error: function(jqXHR, textStatus, errorThrown) {
						console.log(textStatus, errorThrown, jqXHR);
					}
				});
			});
			$('.minus').on('click', function(event) {  
				event.preventDefault();
				$.post({
					url: "http://127.0.0.1:8000/update-cart/",
					data: {
						'id':$(this).attr('id'),
						'quantity':'decrease'
					},
					headers: {
						"Authorization": "Token"+" "+window.localStorage.getItem('token'),
					},
					success: function(response) {
						location.reload();
					},
					error: function(jqXHR, textStatus, errorThrown) {
						console.log(textStatus, errorThrown, jqXHR);
					}
				});
			});
		},
		error: function(jqXHR, textStatus, errorThrown) {
			console.log(jqXHR);
			console.log(textStatus);
			console.log(errorThrown);
		}
	});	
</script>


{% endblock js %}