backend/store/Sale/urls.py
from django.urls import path
from .views import (add_to_productcart, change_productcart,
                    delete_productcart, get_productcart, cart_page, submit_order)


urlpatterns = [
    path('submit-cart/', submit_order, name='submit_order'),
    path('cart/', cart_page, name='cart_page'),
    path('get-cart/', get_productcart, name='get_productcart'),
    path('add-cart/', add_to_productcart, name='add_to_productcart'),
    path('update-cart/', change_productcart, name='change_productcart'),
    path('delete-cart/', delete_productcart, name='delete_productcart'),
]

backend/store/account/urls.py
from django.urls import path
from knox import views as knox_views
from django.contrib.auth.views import LogoutView
from django.conf.urls import url
from account.views import (register_page, phone_validation,
                           otp_validator, login_page, set_password,
                           registeration, LoginView, passwordrecovery_page,
                           change_password, phone_validation_passchange,
                           new_password_replace, dashboard_page,
                           userinfo, edituserinfo, addnewlocation,
                           userlocation, getuserlike, getuserbookmark, getcummentuser)


urlpatterns = [
    path('user-cumment/', getcummentuser, name='getcummentuser'),
    path('user-bookmark/', getuserbookmark, name='getuserbookmark'),
    path('user-likes/', getuserlike, name='getuserlike'),
    path('locations/', userlocation, name='userlocation'),
    path('addlocation/', addnewlocation, name='addnewlocation'),
    path('edit/', edituserinfo, name='edituserinfo'),
    path('userinformations/', userinfo, name='userinfo'),
    path('dashboard/', dashboard_page, name='dashboard_page'),
    path('new_password_replace/', new_password_replace, name='new_password_replace'),
    path('phone_validation_pass/', phone_validation_passchange, name='phone_validation_passchange'),
    path('password_change/', change_password, name='change_password'),
    path('password-recovery/', passwordrecovery_page, name='passwordrecovery_page'),
    path('registration/', register_page, name='register_page'),
    path('user_registeration/', registeration, name='registeration'),
    path('password/', set_password, name='set_password'),
    path('loginuser/', login_page, name='login_page'),
    path('validation_number/', phone_validation, name='phone_validation'),
    path('validation_otp/', otp_validator, name='otp_validator'),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('logout_user/', LogoutView.as_view(), name='logout'),
]

backend/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('app_base.urls', 'app_base'), namespace='app-base')),
    path('', include(('account.urls', 'account'), namespace='account')),
    path('', include(('social.urls', 'social'), namespace='social')),
    path('', include(('Sale.urls', 'Sale'), namespace='Sale')),
    path('admin/', admin.site.urls),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/account/forms.py
# from django import forms
# from django.contrib.auth.forms import ReadOnlyPasswordHashField
# from .models import User


# class LoginForm(forms.Form):
#     phone = forms.IntegerField(label='your phone number.')
#     password = forms.CharField(widget=forms.PasswordInput)


# class VerifyForm(forms.Form):
#     key = forms.IntegerField(label='Please enter otp here')


# class RegisterForm(forms.Form):
#     password = forms.CharField(widget=forms.PasswordInput)
#     password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ('phone',)

#     def clean_phone(self):
#         phone = self.cleaned_data.get('phone')
#         qs = User.objects.filter(phone=phone)
#         if qs.exists():
#             raise forms.ValidationError("phone is taken")
#         return phone

#     def clean_password2(self):
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get("password2")
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError('password dont match.')
#         return password2


# class TempRegisterForm(forms.Form):
#     phone = forms.IntegerField()
#     otp = forms.IntegerField()


# class SetPasswordForm(forms.Form):
#     password = forms.CharField(label='password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)


# class UserAdminCreationForm(forms.ModelForm):
#     password = forms.CharField(label='password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ('phone',)

#     def clean_password2(self):
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get("password2")
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError('password dont match.')
#         return password2

#     def save(self, commit=True):
#         user = super(UserAdminCreationForm, self).save(commit=False)
#         user.set_password(self.cleaned_data["password"])
#         if commit:
#             user.save()
#         return user


# class UserAdminChangeForm(forms.ModelForm):
#     password = ReadOnlyPasswordHashField

#     class Meta:
#         model = User
#         fields = ('phone', 'password', 'active', 'admin')

#     def clean_password(self):
#         return self.initial["password"]

backend/store/account/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.decorators import login_required
from .models import User, OtpNumber, UserLocations
import random
from kavenegar import *
from .serializer import CreateUserSerializer, LoginSerializer, UserSerializer, UserLocationsSerializer
from knox.views import LoginView as KnoxLoginView
from knox.models import AuthToken
from django.contrib.auth import login
from social.serializer import Likeserializer, bookmarkserializer, cummentuserserializer
from social.models import Like, Bookmark, Cumment
import re


reg = "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$"
match_re = re.compile(reg)


def register_page(request):
    return render(request, 'registreation.html')


def passwordrecovery_page(request):
    return render(request, 'passwordrecovery.html')


def login_page(request):
    return render(request, 'login.html')


def set_password(request):
    return render(request, 'set_password.html')


def new_password_replace(request):
    return render(request, 'new_password_replace.html')


@login_required(login_url='/loginuser/')
@permission_classes([IsAuthenticated])
def dashboard_page(request):
    return render(request, 'dashboard.html')


@ api_view(['POST'])
@permission_classes([AllowAny])
def phone_validation(request):
    phonenumber = request.POST.get('phonenumber')
    if phonenumber:
        user = User.objects.filter(phone__iexact=phonenumber)
        if user.exists():
            return Response({
                'status': False,
                'detail': 'این شماره تلفن قبلا در سایت ثبت نام شده است.'
            })
        else:
            key = send_otp(phonenumber)
            if key:
                obj = OtpNumber.objects.filter(phonenumber=phonenumber)
                if obj:
                    objcount = obj.first()
                    if objcount.counts < 7:
                        # api = KavenegarAPI(
                        #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                        # params = {
                        #     'receptor': phonenumber,
                        #     'token': key,
                        #     'template': 'Verify',
                        #     'message': 'Kaveh specialized Web service '
                        # }
                        # response = api.verify_lookup(params)
                        objcount.counts += 1
                        objcount.otp_number = key
                        objcount.save()
                        return Response({
                            'status': True,
                            'detail':
                            'کد تایید ارسال شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail':
                            'تعداد درخواست های تایید هویت پیامکی بیش از حد مجاز است لطفا با بخش پشتیبانی تماس فرمایید.'
                        })
                else:
                    # api = KavenegarAPI(
                    #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                    # params = {
                    #     'receptor': phonenumber,
                    #     'token': key,
                    #     'template': 'Verify',
                    #     'message': 'Kaveh specialized Web service '
                    # }
                    # response = api.verify_lookup(params)
                    OtpNumber.objects.create(phonenumber=phonenumber, otp_number=key)
                    return Response({
                        'status': True,
                        'detail':
                            'کد تایید ارسال شد.'
                    })
            else:
                return Response({
                    'status': False,
                    'detail': 'send otp error.'
                })
    else:
        return Response({
            'status': False,
            'detail': 'شماره تلفن وارد نشده است.'
        })


def send_otp(phone):
    if phone:
        key = random.randint(999, 9999)
        return key
    else:
        return False


@ api_view(['POST'])
@permission_classes([AllowAny])
def otp_validator(request):
    otp_number = request.POST.get('otp')
    phonenumber = request.POST.get('phonenumber')
    if otp_number and phonenumber:
        phone = OtpNumber.objects.filter(phonenumber=phonenumber, otp_number=otp_number)
        obj = phone.first()
        if obj and obj.otp_number == otp_number:
            obj.validate = True
            obj.save()
            return Response({
                'status': True,
                'detail': 'کاربر با موفقیت ثبت نام شد.'
            })
        else:
            return Response({
                'status': False,
                'detail': 'کد تایید منطبق نیست.'
            })
    else:
        return Response({
            'status': False,
            'detail': 'کد تایید وارد نشده است.'
        })


@ api_view(['POST'])
@permission_classes([AllowAny])
def registeration(request):
    password = request.POST.get('password')
    phonenumber = request.POST.get('phonenumber')
    if phonenumber and password:
        res = re.search(match_re, password)
        if res:
            myobj = OtpNumber.objects.filter(phonenumber=phonenumber)
            obj = myobj.first()
            if obj:
                if obj.validate:
                    temp_data = {
                        'phone': phonenumber,
                        'password': password,
                    }
                    serializer = CreateUserSerializer(data=temp_data)
                    serializer.is_valid(raise_exception=True)
                    user = serializer.save()
                    obj.delete()
                    if user:
                        return Response({
                            'status': True,
                            'user': UserSerializer(user).data,
                            'token': AuthToken.objects.create(user)[1],
                            'detail': 'کاربر با موفقیت ثبت نام شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail': 'اوه اوه یه مشکلی پیش اومده.'
                        })
                else:
                    return Response({
                        'status': False,
                        'detail': 'otp تایید نشده است.'
                    })
            else:
                return Response({
                    'status': False,
                    'detail': 'شماره موبایل پیدا نشد.'
                })
        else:
            return Response({
                'status': False,
                'detail': 'طول پسورد باید حداقل 8 کاراکتر باشد و شامل حداقل یک عدد و یک حرف باشد.'
            })
    else:
        return Response({
            'status': False,
            'detail': 'شماره موبایل یا رمز عبرور وارد نشده است.'
        })


class LoginView(KnoxLoginView):
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super().post(request, format=None)


@ api_view(['POST'])
@permission_classes([AllowAny])
def phone_validation_passchange(request):
    phonenumber = request.POST.get('phonenumber')
    if phonenumber:
        user = User.objects.filter(phone__iexact=phonenumber)
        if user.exists():
            key = send_otp(phonenumber)
            if key:
                obj = OtpNumber.objects.filter(phonenumber=phonenumber)
                if obj:
                    objcount = obj.first()
                    if objcount.counts < 7:
                        # api = KavenegarAPI(
                        #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                        # params = {
                        #     'receptor': phonenumber,
                        #     'token': key,
                        #     'template': 'Verify',
                        #     'message': 'Kaveh specialized Web service '
                        # }
                        # response = api.verify_lookup(params)
                        objcount.counts += 1
                        objcount.otp_number = key
                        objcount.save()
                        return Response({
                            'status': True,
                            'detail':
                            'کد تایید ارسال شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail':
                            'تعداد درخواست های تایید هویت پیامکی بیش از حد مجاز است لطفا با بخش پشتیبانی تماس فرمایید.'
                        })
                else:
                    # api = KavenegarAPI(
                    #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                    # params = {
                    #     'receptor': phonenumber,
                    #     'token': key,
                    #     'template': 'Verify',
                    #     'message': 'Kaveh specialized Web service '
                    # }
                    # response = api.verify_lookup(params)
                    OtpNumber.objects.create(phonenumber=phonenumber, otp_number=key)
                    return Response({
                        'status': True,
                        'detail':
                            'کد تایید ارسال شد.'

backend/store/account/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}

<div class="container">
	<div class="row" style="justify-content:center;">
		<div class="col-md-6 m-5">
			<div class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">ورود با شماره تلفن همراه.</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">شماره تلفن همراه:</div>
					<input id="phonenumber" class="form-control form-control-lg" type="text" placeholder="0 9 * * * * * * * * *" style="direction:ltr;">
				</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">رمز عبور</div>
					<input id="password" class="form-control form-control-lg" type="password" placeholder="رمز عبور خود را وارد کنید" >
				</div>
				<a href="">
					<div id="login" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
						ورود
					</div>
				</a>
				<div class="text-danger" id="error" style="font-size:14px;"></div>
				<div class="p-2"><a class="text-decoration-none" href="{% url 'account:passwordrecovery_page' %}" style="font-size:14px;">رمز عبور خود را فراموش كرده ام.</a></div>
				<div class="p-2">
					<span style="font-size:14px;">اگر در فروشگاه حساب کاربری ندارید ثبت نام کنید.</span>
					<a class="text-decoration-none" href="{% url 'account:register_page' %}"><span class="border border-primary p-2" style="font-size:14px;border-radius:5px;">ایجاد حساب کاربری</span></a>
				</div>
			</div>
		</div>
	</div>
</div>

{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}

<script>
	$('#login').on('click', function(event) {  
		event.preventDefault();
		$('#error').html('');
		$( "#error" ).removeClass('p-2');
		$.post({
			url: "http://127.0.0.1:8000/login/",
			data: {
				'phone':$('#phonenumber').val(),
				'password':$('#password').val(),
			},
			success: function(response) {
				window.localStorage.setItem('token', response.token);
				window.location.replace('{% url 'app_base:home' %}');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(textStatus, errorThrown, jqXHR);
				if (jqXHR.responseJSON.detail) {
					$('#error').append(jqXHR.responseJSON.detail);
					$( "#error" ).addClass('p-2');  
				}
			}
		});
	});
</script>




{% endblock js %}

backend/store/account/templates/new_password_replace.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}
<div class="container">
	<div class="row" style="justify-content:center;">
		<div class="col-md-6 m-5">
			<div id="pass" class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">رمز عبور جديد خودرا وارد كنيد.</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">رمز عبور</div>
					<input id="password" class="form-control form-control-lg" type="password" placeholder="رمز عبور خود را وارد کنید" >
				</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">تکرار رمز عبور</div>
					<input id="password2" class="form-control form-control-lg" type="password" placeholder="تکرار رمز عبور خود را وارد کنید" >
				</div>
				<a href="#">
					<div id="set_password" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
						ثبت رمز عبور
					</div>
				</a>
				<div class="" id="error" style="font-size:14px;"></div>
			</div>
		</div>
	</div>
</div>
{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}
<script>
	$('#set_password').on('click', function(event) {  
		event.preventDefault();
		$('#error').html('');
		$( "#error" ).removeClass('p-2 text-danger text-success');
		if ($('#password').val() == $('#password2').val()) {
			$.post({
				url: "http://127.0.0.1:8000/password_change/",
				data: {
					'phonenumber':window.localStorage.getItem('userphonehistory'),
					'password':$('#password').val(),
				},
				success: function(response) {
					$('#error').html('');
					$( "#error" ).removeClass('p-2 text-danger text-success');
					if (response.status == false) {
						$('#error').append(response.detail);
						$( "#error" ).addClass('p-2 text-danger');
					}
					else if(response.status == true){
						window.localStorage.removeItem('userphonehistory');
						$('#error').append(response.detail);
						$( "#error" ).addClass('p-2 text-success');
						html=`
						<div class="p-2 mt-4">
						<span style="font-size:14px;">اكنون با مز جديد ميتوانيد وارد حساب كاربري خود شويد.</span>
						<a class="text-decoration-none" href="{% url 'account:login_page' %}"><span class="border border-primary p-2" style="font-size:14px;border-radius:5px;">ورود به حساب کاربری</span></a>
						</div>`
						$('#pass').append(html);

					}
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(textStatus, errorThrown, jqXHR);
				}
			});
		}else{
			$('#error').append('رمز عبور با تکرار رمز عبور برابر نیست.');
			$( "#error" ).addClass('p-2 text-danger');
		}
	});



	
</script>
{% endblock js %}

backend/store/account/templates/passwordrecovery.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}
<div class="container">
	<div class="row" style="justify-content:center;">
		<div id="reg" class="col-md-6 m-5">
			<div id="register" class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">شماره تلفن همراه خود را وارد كنيد.</div>
				<div>
					<div class="p-2">شماره تلفن همراه:</div>
					<input id="phonenumber" class="form-control form-control-lg" type="text" placeholder="0 9 * * * * * * * * *" style="direction:ltr;">
				</div>
				<a href="">
					<div id="recive_otp" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
						دریافت کد تایید
					</div>
				</a>
				<div class="text-danger" id="error" style="font-size:14px;"></div>
				<div class="p-2 mt-3">
					<span style="font-size:14px;">اگر در فروشگاه حساب کاربری ندارید ثبت نام کنید.</span>
					<a class="text-decoration-none" href="{% url 'account:register_page' %}"><span class="border border-primary p-2" style="font-size:14px;border-radius:5px;">ایجاد حساب کاربری</span></a>
				</div>
			</div>
		</div>
	</div>
</div>
{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}
<script>
	$('#recive_otp').on('click', function(event) { 
		event.preventDefault();
		$.post({
			url: "http://127.0.0.1:8000/phone_validation_pass/",
			data: {
				'phonenumber':$('#phonenumber').val(),
			},
			success: function(response) {
				$('#error').html('');
				$( "#error" ).removeClass('p-2');
				if (response.status == false) {
					$('#error').append(response.detail);
					$( "#error" ).addClass('p-2');
				}
				else{
					$('#register').hide();
					html=`
					<a class="text-decoration-none" href="{% url 'account:register_page' %}"><div class="m-2 text-dark"><i class="fa fa-arrow-right ml-2"></i>بازگشت به قبل</div></a>
					<div id="register" class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
					<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">کد تایید ارسال شده را وارد کنید.</div>
					<div>
					<div class="p-2">کد تایید</div>
					<input id="otp_number" class="form-control form-control-lg" type="text" placeholder="* * * *" style="direction:ltr;">
					</div>
					<a href="">
					<div id="validate_otp" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
					ثبت کد 
					</div>
					</a>
					<div class="text-danger" id="errorotp" style="font-size:14px;"></div>
					<div class="p-2 mt-2">
					<span>اگر در فروشگاه حساب کاربری ندارید ثبت نام کنید.</span>
					<a class="text-decoration-none" href=""><span>ایجاد حساب کاربری</span></a>
					</div>
					</div>`
					$('#reg').append(html);
				}
				$('#validate_otp').on('click', function(event) { 
					event.preventDefault();
					window.localStorage.setItem('userphonehistory', $('#phonenumber').val());
					$.post({
						url: "http://127.0.0.1:8000/validation_otp/",
						data: {
							'otp':$('#otp_number').val(),
							'phonenumber':$('#phonenumber').val(),
						},
						success: function(response) {
							$('#errorotp').html('');
							$( "#errorotp" ).removeClass('p-2');
							if (response.status == false) {
								$('#errorotp').append(response.detail);
								$( "#errorotp" ).addClass('p-2');
							}
							else if(response.status == true){
								window.location.replace('{% url 'account:new_password_replace' %}');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.log(textStatus, errorThrown, jqXHR);
						}
					});
				});
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(textStatus, errorThrown, jqXHR);
			}
		});
	});
</script>
{% endblock js %}

backend/store/account/templates/registreation.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}
<div class="container">
	<div class="row" style="justify-content:center;">
		<div id="reg" class="col-md-6 m-5">
			<div id="register" class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">ثبت نام با شماره تلفن همراه</div>
				<div>
					<div class="p-2">شماره تلفن همراه:</div>
					<input id="phonenumber" class="form-control form-control-lg" type="text" placeholder="0 9 * * * * * * * * *" style="direction:ltr;">
				</div>
				<a href="">
					<div id="recive_otp" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
						دریافت کد تایید
					</div>
				</a>
				<div class="text-danger" id="error" style="font-size:14px;"></div>
				<div class="p-2 mt-4">
					<span style="font-size:14px;">اگر در فروشگاه حساب کاربری دارید دکمه ورود را بزنید.</span>
					<a class="text-decoration-none" href="{% url 'account:login_page' %}"><span class="border border-primary p-2" style="font-size:14px;border-radius:5px;">ورود به حساب کاربری</span></a>
				</div>
			</div>
		</div>
	</div>
</div>
{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}
<script>
	$('#recive_otp').on('click', function(event) { 
		event.preventDefault();
		$.post({
			url: "http://127.0.0.1:8000/validation_number/",
			data: {
				'phonenumber':$('#phonenumber').val(),
			},
			success: function(response) {
				$('#error').html('');
				$( "#error" ).removeClass('p-2');
				if (response.status == false) {
					$('#error').append(response.detail);
					$( "#error" ).addClass('p-2');
				}
				else{
					$('#register').hide();
					html=`
					<a class="text-decoration-none" href="{% url 'account:register_page' %}"><div class="m-2 text-dark"><i class="fa fa-arrow-right ml-2"></i>بازگشت به قبل</div></a>
					<div id="register" class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
					<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">کد تایید ارسال شده را وارد کنید.</div>
					<div>
					<div class="p-2">کد تایید</div>
					<input id="otp_number" class="form-control form-control-lg" type="text" placeholder="* * * *" style="direction:ltr;">
					</div>
					<a href="">
					<div id="validate_otp" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
					ثبت کد 
					</div>
					</a>
					<div class="text-danger" id="errorotp" style="font-size:14px;"></div>
					<div class="p-2 mt-2">
					<span>اگر در فروشگاه حساب کاربری ندارید ثبت نام کنید.</span>
					<a class="text-decoration-none" href=""><span>ایجاد حساب کاربری</span></a>
					</div>
					</div>`
					$('#reg').append(html);
				}
				$('#validate_otp').on('click', function(event) { 
					event.preventDefault();
					window.localStorage.setItem('userphonehistory', $('#phonenumber').val());
					$.post({
						url: "http://127.0.0.1:8000/validation_otp/",
						data: {
							'otp':$('#otp_number').val(),
							'phonenumber':$('#phonenumber').val(),
						},
						success: function(response) {
							$('#errorotp').html('');
							$( "#errorotp" ).removeClass('p-2');
							if (response.status == false) {
								$('#errorotp').append(response.detail);
								$( "#errorotp" ).addClass('p-2');
							}
							else if(response.status == true){
								window.location.replace('{% url 'account:set_password' %}');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.log(textStatus, errorThrown, jqXHR);
						}
					});
				});
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(textStatus, errorThrown, jqXHR);
			}
		});
	});
</script>
{% endblock js %}